#!/usr/bin/env bash
# This script tells a story based on /etc/passwd entries

while IFS=: read -r username _ uid gid _ home shell info
do
    if [ -z "$info" ]; then
        info="$username"
    fi
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd 