#!/bin/bash

# Create PID file
echo $$ > /var/run/myscript.pid

# Signal handlers
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done 