#!/usr/bin/env bash
# This script creates a PID file and runs an infinite loop that prints "To infinity and beyond" every 2 seconds
# Create PID file
echo $$ > /var/run/myscript.pid

# Signal handlers
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done 