#!/bin/bash

case "$1" in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0 