#!/usr/bin/env bash
# This script lists the PID and name of processes that contain the word "bash" in their name

for pid in /proc/[0-9]*; do
    cmdline_file="$pid/comm"
    if [ -f "$cmdline_file" ]; then
        cmd=$(cat "$cmdline_file" 2>/dev/null)
        if [[ "$cmd" == *bash* ]]; then
            echo "${pid##*/} $cmd"
        fi
    fi
done
